[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader_api = "0.11"
x86_64 = "0.14.10"
# uefi = "0.19.1"

spin = { version = "0.9.5", features = ["mutex"] }
log = "0.4"
noto-sans-mono-bitmap = { version = "0.2.0", default-features = false, features = ["unicode-basic-latin", "regular", "size_20", "size_32"] }
