[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader_api = "0.11"
x86_64 = "0.14.10"
raw-cpuid = "10.6.1"
# uefi = "0.19.1"

spin = { version = "0.9.5", features = ["mutex"] }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
slab_allocator_rs = "1.0.2"

log = "0.4"
noto-sans-mono-bitmap = { version = "0.2.0", default-features = false, features = ["unicode-basic-latin", "regular", "size_16", "size_20", "size_32"] }

# hashmap_core = "0.1.8"

# Cranelift compiler
# [dependencies.target-lexicon]
# version = "0.0.3"
# default-features = false

cranelift-native = { path = "../cranelift-no_std/cranelift-native", default-features = false, features = ["core"] }
cranelift-wasm = { path = "../cranelift-no_std/cranelift-wasm", default-features = false, features = ["core"] }
# [dependencies.cranelift-codegen]
# version = "0.82"
# default-features = false
# features = ["core"]

# [dependencies.cranelift-frontend]
# version = "0.33"
# default-features = false
# features = ["core"]

# [dependencies.cranelift-wasm]
# version = "0.33"
# default-features = false
# features = ["core"]

# [dependencies.cranelift-native]
# version = "0.43.1"
# default-features = false
# features = ["core"]
